services:
  web:
    depends_on:
      test:
        condition: service_healthy

  mariadb:
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 2s

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:${DB_PASSWORD}@mariadb/${DB_DATABASE}
    healthcheck:
      test: ['CMD', 'test', '-f', '/tmp/prisma-ready']
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
