name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_web:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
    with:
      output: image
      push: true
      meta-images: ghcr.io/tasktix/tasktix-web
      annotations: |
        org.opencontainers.image.source=https://github.com/Tasktix/Tasktix
        org.opencontainers.image.description=A powerful and flexible task-tracking tool for all.
        org.opencontainers.image.licenses=AGPL-3.0-or-later
      meta-tags: latest
      platforms: linux/amd64,linux/arm64
      fail-fast: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build_deploy:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    with:
      file: Dockerfile.deploy
      output: image
      push: true
      meta-images: ghcr.io/tasktix/tasktix-deploy
      annotations: |
        org.opencontainers.image.description=A powerful and flexible task-tracking tool for all.
        org.opencontainers.image.licenses=AGPL-3.0-or-later
      meta-tags: latest
      platforms: linux/amd64,linux/arm64
      fail-fast: true
