name: End-to_End Test

on: [pull_request]

permissions:
  contents: read

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Cypress binary
        id: cache-cypress
        uses: actions/cache@v3
        with:
          path: .cache/Cypress
          key: cypress-${{ runner.os }}-v15.1.0
      - name: Install Cypress binary if needed
        if: steps.cache-cypress.outputs.cache-hit != 'true'
        run: npx cypress install
      - name: Test
        run: npm run test:cy
      - name: Save artifacts from failed tests
        uses: actions/upload-artifact@v4
        with:
          name: e2e-videos
          path: cypress/videos/
